
BLOCK_INTERVAL_SECONDS = 60*10
BLOCK_DIFFICULTY_CYCLE = 6*24*7

NETWORK_SPREADING_SECONDS = 60*10 # 10 minutes in real world
MAX_MESSAGE_DELAY_SECONDS = NETWORK_SPREADING_SECONDS * 6
FROZEN_BLOCK_NO = 100

NEIGHBOURHOODS_HOPS = 2

MINING = False

BOOTSTRAP_BY_PORT_NO = False

NODE_DIVISION = False

PYTHON_EXECUTABLE = 'python3'

DASHBOARD_PORT = 8000
