
BLOCK_INTERVAL_SECONDS = 15
BLOCK_DIFFICULTY_CYCLE = 6

NETWORK_SPREADING_SECONDS = 15 # 10 minutes in real world
MAX_MESSAGE_DELAY_SECONDS = NETWORK_SPREADING_SECONDS * 6

NEIGHBOURHOODS_HOPS = 2

MINING = True
EASY_MINING = True

BOOTSTRAP_BY_PORT_NO = False

SHARDING = True

PYTHON_EXECUTABLE = 'python3'

DASHBOARD_PORT = 9000

TOKEN_SHARES = 10**15 # for JS only has 2**53
